752:2xvfb-run --auto-servernum '--server-args=-screen 0 1024x768x24' nosetests --verbosity=3 --exe -s pandas
 in dir /home/buildslave/nd-bb-slave-sparc-wheezy/pandas-py3_x-wheezy-sparc/build/venv (timeout 7200 secs)
 watching logfiles {}
 argv: ['xvfb-run', '--auto-servernum', '--server-args=-screen 0 1024x768x24', 'nosetests', '--verbosity=3', '--exe', '-s', 'pandas']
 environment:
  HOME=/home/buildslave
  LOGNAME=buildslave
  MAIL=/var/mail/buildslave
  PATH=/home/buildslave/nd-bb-slave-sparc-wheezy/pandas-py3_x-wheezy-sparc/build/venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
  PWD=/home/buildslave/nd-bb-slave-sparc-wheezy/pandas-py3_x-wheezy-sparc/build/venv
  SHELL=/bin/sh
  TERM=xterm
  USER=buildslave
 using PTY: False
,1822:0nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
Failure: ImportError (No module named six) ... ERROR

======================================================================
ERROR: Failure: ImportError (No module named six)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/nd-bb-slave-sparc-wheezy/pandas-py3_x-wheezy-sparc/build/venv/lib/python3.2/site-packages/nose/failure.py", line 38, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/buildslave/nd-bb-slave-sparc-wheezy/pandas-py3_x-wheezy-sparc/build/venv/lib/python3.2/site-packages/nose/loader.py", line 402, in loadTestsFromName
    module = resolve_name(addr.module)
  File "/home/buildslave/nd-bb-slave-sparc-wheezy/pandas-py3_x-wheezy-sparc/build/venv/lib/python3.2/site-packages/nose/util.py", line 311, in resolve_name
    module = __import__('.'.join(parts_copy))
  File "/home/buildslave/nd-bb-slave-sparc-wheezy/pandas-py3_x-wheezy-sparc/build/venv/lib/python3.2/site-packages/pandas-0.12.0_59_g6c304c7-py3.2-linux-sparc64.egg/pandas/__init__.py", line 25, in <module>
    import pandas.core.config_init
  File "/home/buildslave/nd-bb-slave-sparc-wheezy/pandas-py3_x-wheezy-sparc/build/venv/lib/python3.2/site-packages/pandas-0.12.0_59_g6c304c7-py3.2-linux-sparc64.egg/pandas/core/config_init.py", line 1, in <module>
    import pandas.core.config as cf
  File "/home/buildslave/nd-bb-slave-sparc-wheezy/pandas-py3_x-wheezy-sparc/build/venv/lib/python3.2/site-packages/pandas-0.12.0_59_g6c304c7-py3.2-linux-sparc64.egg/pandas/core/config.py", line 55, in <module>
    import six
ImportError: No module named six

----------------------------------------------------------------------
Ran 1 test in 0.010s

FAILED (errors=1)
,56:2program finished with exit code 1
elapsedTime=4.272770
,